### PR TITLE
Require zestreleaser.towncrier.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
And start using towncrier for our own ``CHANGES.rst``.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@gforcada What PRs do you expect for the buildout.coredev branches?

I will create PRs for a few packages to start using `towncrier`, starting with `plone.app.upgrade`. Review is helpful there.

I will also try to create a (bash) script for the basics that need to be done for converting a package to use `towncrier`. Editing the existing `CHANGES.rst` and reverse migrating it to news files will be too much to ask. But a few of the boring tasks should be easy to automate.

**Comment by mauritsvanrees** [comment]
Bash script is here: https://gist.github.com/mauritsvanrees/92c40bc16ceaf3c375d81c995b4552c4

**Comment by gforcada** [comment]
@mauritsvanrees I *guess* I was thinking about pinning towncrier and its dependencies in versions.cfg, adding zestreleaser.towncrier on another cfg etc etc

**Comment by mauritsvanrees** [comment]
Ah, right, good point. Will do.

**Pull request merged**
