### PR TITLE
Update other Plone core branches when releasing packages

### PR DESCRIPTION
**Pull request by gforcada**
@esteele @mauritsvanrees there you go, I tested it with a few packages until I finally fixed all the errors, see plone.synchronize as the last release made across all buildout.coredev branches.

### CODE REVIEW

**Comment by gforcada** [comment]
:sweat_smile: I think Jenkins is going to be busy for a few minutes due to all my attempts

**Comment by gforcada** [comment]
It might be too late at night, but I don't get your comment about the expected workflow, if it is done as a zest.releaser plugin the current working directory is the package, so ``../`` would be ``src`` folder of ``buildout.coredev``. Do you have one checkout of buildout.coredev next to each other, one for each branch? Then we would have to document that you need this filesystem layout to actually be able to release in multiple versions at the same time.

As for outdated branches, yes, it could happen, we might wrap the ``update_core`` call with a try except and report if there was a problem, so that the user making releases knows that at least a branch needs to be manually updated? :thinking:

**Comment by gforcada** [comment]
I just did that (add a try..except) would that be enough safeness?

**Comment by mauritsvanrees** [comment]
> Do you have one checkout of buildout.coredev next to each other, one for each branch?

Yes.

Well, I tried your branch and I released `Products.CMFDynamicViewFTI` within 5.1 and at the same time to the other three branches as well, and that seems to have gone absolutely fine.

I guess the danger is that you release multiple packages, and do not push all changes in between so as not to swamp Jenkins, and then at the end you forget to push all branches, so you have perfectly fine commits that stay there on your machine. But that happens much more easily with current plone.releaser: you makes a release and forget to check and update the other branches, whether they are in different directories or not.

All in all: I am happy! This will safe a lot of work and typos and other mistakes.
Thank you! I will merge.

**Comment by mauritsvanrees** [comment]
If you have a 5.1 checkout, then the other local branches can easily get outdated, which may interfere with this. I have just created this bash script which updates all my major coredev checkouts and branches. It is hardcoded for my machine, but it may be helpful for others.

```
#!/bin/sh
BASEDIR=~/community/plone-coredev
for checkout in 4.3 5.0 5.1 5.2; do
    echo
    echo "====================="
    cd $BASEDIR/$checkout
    pwd
    git fetch
    for branch in 4.3 5.0 5.1 5.2; do
        git checkout $branch
        git merge --ff-only
    done
    # Go back to original branch
    git checkout $checkout
done
```

**Pull request merged**
