### PR TITLE
Refactor package check

### PR DESCRIPTION
**Pull request by gforcada**
@esteele with this new command (``./bin/manage jenkins``) I think we can finally fix https://github.com/plone/jenkins.plone.org/issues/102

@esteele @tisto @mauritsvanrees could you try to make a release of a package with this branch? I hope I got it right, but as I did quite a refactoring I may have introduced bugs without noticing...

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have done a few releases. No problems.
Then I switched to your branch... Still no problems. :-)

From the 'manage' commands I only tested the 'checkPypi' command and that one was fine.

**Comment by gforcada** [comment]
I manually merged the branch, let's see if anyone complains about it :)

**Comment by esteele** [comment]
Perfect. Thanks!

**Comment by tisto** [comment]
@gforcada Cool. Thx!

**Pull request closed without merging**
