### PR TITLE
Add buildout2pip command

### PR DESCRIPTION
**Pull request by mauritsvanrees**
We already had `bin/manage version2constraints`.  Now we have `bin/manage buildout2pip`.  It translates `versions*.cfg`, `checkouts*.cfg` and `sources*.cfg` to their pip/mxdev equivalents.

This aims to create what @thet added in https://github.com/plone/buildout.coredev/pull/903.  @jensens there suggested `mxsources.ini` and `mxcheckouts.ini` and I went with that.

The base code has tests, but I would like to add a few more high level tests.  But you can try it out in buildout.coredev.  `plone.releaser` is already in the checkouts.  So go to `src/plone.releaser` and checkout the branch of this PR, and then in the buildout run `bin/manage buildout2pip` and see what files it creates.

Note that this PR mostly removes support for a `mxdev.ini` file with both sources and checkouts in one: you must separate them into two files.  This matches what we are doing in coredev with buildout since years.

Also, I hardcode putting `default-use = false` in `mxsources.ini`, without looking at the `[buildout] always-checkout` value in `checkouts.cfg`.  We may want to make clearer in the readme that this package is really only meant for core Plone development, not as a package for general use.  It just gets too complicated if we want to support use cases that we do not have in core Plone.

### CODE REVIEW

**Comment by wesleybl** [comment]
@mauritsvanrees this is one step towards a "pip.coredev"? Will you plan on using pip instead of buildout someday?

**Comment by mauritsvanrees** [comment]
> @mauritsvanrees this is one step towards a "pip.coredev"? Will you plan on using pip instead of buildout someday?

@wesleybl This brings buildout and pip more on the same level, but still with buildout leading, being the source.
Next step would be to create a `pip2buildout` command, and then pip can become leading.  We could already do that in 6.1, but needs more work in `buildout.coredev`.
Then at some point we could completely drop buildout.  But that would at the earliest be in Plone 7.0.  Until then I definitely want to support buildout.  Unless it [breaks](https://github.com/buildout/buildout/issues/647)...

And yes, at some point (Plone 7.0?) we might rename or copy `buildout.coredev` to `pip.coredev`.  Probably just `coredev`: I already am often not sure whether it is `buildout.coredev` or `coredev.buildout`. :-)

**Comment by jensens** [comment]
this should generate `ini` files not `txt`.

**Comment by mauritsvanrees** [comment]
> this should generate `ini` files not `txt`.

Done.  And I have added tests.

This is now ready for review.

**Review by jensens — APPROVED** [review]

**Pull request merged**
